feat: migrate to alloy primitivres
ralexstokes/ssz-rs pull request #104
Opened 2023-09-18 00:12 UTC by PatStiles

Seeks to close #94

2023-09-18 00:14 UTC, PatStiles commented
@ralexstokes Let me know if i am on the right track here.

2023-09-18 02:55 UTC, PatStiles commented
@ralexstokes let me know if I'm on the right track. I've successfully remvoed U256.

2023-09-18 14:14 UTC, ralexstokes requested changes
we can use the built-in rust types

the only thing we need to do here is migrate the currently defined `U256` type to the one from alloy

e.g. we won't need to change any of the calling code, so all of the `use alloy_primitives::U256` should disappear

2023-09-18 20:43 UTC, ralexstokes commented on ssz-rs/src/lib.rs
> +    pub use alloy_primitives::U256;
so this should re-export our type (which just happens to be alloy's `U256`

```suggestion
    pub use uint::U256;
```

(although this line should already be present above somehow)

2023-10-20 16:44 UTC, ralexstokes commented
wrapped this up in #113

2023-10-20 16:44 UTC, closed without merging